################################
#  Parameters
################################
/**:
  filter_node:
    ros__parameters:
      node_frequency: 10.0
      publish_all_steps: true

      filters: 
        - "" 
      measurements:
        - "gnss"
        - "imu"
        - "utm_ned"
        - "altimeter"
        - "thruster_rpm"
      
      # plugins:
        