/**:
  ros__parameters:
    actuation:
      static_thruster_allocation:
        node_frequency: 10
        topics:
          subscribers:
            body_wrench_request: "/#vehicle#/actuation/body_wrench_request"
          publishers:
            thruster_force: "/#vehicle#/actuation/thruster_force"
      thruster_rudder_allocation:
        node_frequency: 10
        topics:
          subscribers:
            body_wrench_request: "/#vehicle#/actuation/body_wrench_request"
          publishers:
            thruster_force: "/#vehicle#/actuation/thruster_force"
            rudder_angle: "/#vehicle#/actuation/rudder_angle"
    nav:
      filter_handler:
        node_frequency: 10
        topics:
          subscribers:
            sample_and_hold: "/#vehicle#/nav/sample_and_hold/state"
            complementary: "/#vehicle#/nav/complementary/state"
          publishers:
            state: "/#vehicle#/nav/filter/state"
          services:
            change_filter: "/#vehicle#/nav/change_filter"
      sample_and_hold:
        node_frequency: 10
        topics:
          subscribers:
            measurement: "/#vehicle#/measurement"
          publishers:
            state: "/#vehicle#/nav/sample_and_hold/state"