##############################
#   Default ROS interfaces   #
##############################

# "/**" is needed for nodes to find their params despite the 
# "/vehicle0/<meta_package>/"<node_name>. the /**/ essentially 
# leaves only the "node_name" as a key.
/**:
########################
# ---  Navigation  --- #
########################
  filter_handler:
    ros__parameters:  
      topics:
        subscribers:
          sample_and_hold: "/#vehicle#/nav/sample_and_hold/state"
          low_pass: "/#vehicle#/nav/low_pass/state"
        publishers:
          state: "/#vehicle#/nav/filter/state"
          nav_sat_fix: "/#vehicle#/nav/filter/nav_sat_fix"
        services:
          change_filter: "/#vehicle#/nav/change_filter"
  sample_and_hold:
    ros__parameters:
      topics:
        subscribers:
          measurement: "/#vehicle#/measurement"
        publishers:
          state: "/#vehicle#/nav/sample_and_hold/state"
  low_pass:
    ros__parameters:
      topics:
        subscribers:
          measurement: "/#vehicle#/measurement"
        publishers:
          state: "/#vehicle#/nav/low_pass/state"
#######################
# ---  Actuation  --- #
#######################  
  rpm_conversion:
    ros__parameters:
      topics:
        subscribers:
          thruster_force: "/#vehicle#/actuation/thruster_force"
          nav_state: "/#vehicle#/nav/filter/state"
        publishers:
          rpm_command: "/#vehicle#/actuation/rpm_command"
  throttle_conversion:
    ros__parameters:
      topics:
        subscribers:
          rpm_command: "/#vehicle#/actuation/rpm_command"
        publishers:
          throttle_command: "/#vehicle#/throttle_command"
  static_thruster_allocation:
    ros__parameters:
      topics:
        subscribers:
          body_wrench_request: "/#vehicle#/actuation/body_wrench_request"
        publishers:
          thruster_force: "/#vehicle#/actuation/thruster_force"
  thruster_rudder_allocation:
    ros__parameters:
      topics:
        subscribers:
          body_wrench_request: "/#vehicle#/actuation/body_wrench_request"
          nav_state: "/#vehicle#/nav/filter/state"
          mission_status: "/#vehicle#/mission_status"
        publishers:
          thruster_force: "/#vehicle#/actuation/thruster_force"
          rudder_angle_ref: "/#vehicle#/actuation/rudder_angle_ref"
  wrench_manager:
    ros__parameters:
      topics:
        subscribers:
          thrust_x: "/#vehicle#/actuation/thrust_x"
          thrust_y: "/#vehicle#/actuation/thrust_y"
          thrust_z: "/#vehicle#/actuation/thrust_z"
          torque_x: "/#vehicle#/actuation/torque_x"
          torque_y: "/#vehicle#/actuation/torque_y"
          torque_z: "/#vehicle#/actuation/torque_z"
        publishers:
          body_wrench_request: "/#vehicle#/actuation/body_wrench_request"

########################
# ---  Inner-Loop  --- #
########################
  pid:
    ros__parameters:
      topics:
        subscribers:
          nav_state: "/#vehicle#/nav/filter/state"
          surge_ref: "/#vehicle#/control/ref/surge"
          sway_ref: "/#vehicle#/control/ref/sway"
          heave_ref: "/#vehicle#/control/ref/heave"
          yaw_ref: "/#vehicle#/control/ref/yaw"
          pitch_ref: "/#vehicle#/control/ref/pitch"
          roll_ref: "/#vehicle#/control/ref/roll"
          yaw_rate_ref: "/#vehicle#/control/ref/yaw_rate"
          pitch_rate_ref: "/#vehicle#/control/ref/pitch_rate"
          roll_rate_ref: "/#vehicle#/control/ref/roll_rate"
        publishers:
          thrust_x: "/#vehicle#/actuation/thrust_x"
          thrust_y: "/#vehicle#/actuation/thrust_y"
          thrust_z: "/#vehicle#/actuation/thrust_z"
          torque_x: "/#vehicle#/actuation/torque_x"
          torque_y: "/#vehicle#/actuation/torque_y"
          torque_z: "/#vehicle#/actuation/torque_z"
          debug:
            yaw: "/#vehicle#/control/inner_loop/pid/yaw/debug"
        services:
          change_params: "/#vehicle#/control/pid/change_params"
          course_control: "/#vehicle#/control/pid/course_control"
  open_loop:
    ros__parameters:
      topics:
        subscribers:
          surge_ref: "/#vehicle#/control/ref/surge"
          mission_status: "/#vehicle#/mission_status"
        publishers:
          rpm_command: "/#vehicle#/actuation/rpm_command"
          # thrust_y: "/#vehicle#/actuation/thrust_y"
          # thrust_z: "/#vehicle#/actuation/thrust_z"
          # torque_x: "/#vehicle#/actuation/torque_x"
          # torque_y: "/#vehicle#/actuation/torque_y"
          # torque_z: "/#vehicle#/actuation/torque_z"

########################
# ---  Outer-Loop  --- #
########################
  waypoint:
    ros__parameters:
      topics:
        subscribers:
          mission_status: "/#vehicle#/mission_status"
          state: "/#vehicle#/nav/filter/state"
          turn_radius_flag: "/#vehicle#/turn_radius_flag"
        publishers:
          yaw_ref: "/#vehicle#/control/ref/yaw"
          yaw_rate_ref: "/#vehicle#/control/ref/yaw_rate"
          u_ref: "/#vehicle#/control/ref/surge"
          v_ref: "/#vehicle#/control/ref/sway"
          mission_status: "/#vehicle#/mission_status"
        services:
          wp_standard: "/#vehicle#/control/outer_loop/send_wp_standard"
          wp_loose: "/#vehicle#/control/outer_loop/send_wp_loose"
          wp_heading: "/#vehicle#/control/outer_loop/send_wp_heading"
  path_following:
    ros__parameters:
      topics:
        subscribers:
          mission_status: "/#vehicle#/mission_status"
          state: "/#vehicle#/nav/filter/state"
          path_data: "/#vehicle#/control/outer_loop/path_data"
          vc: "/#vehicle#/control/outer_loop/path_following/vc"
        publishers:
          mission_status: "/#vehicle#/mission_status"
          surge: "/#vehicle#/control/ref/surge"
          sway: "/#vehicle#/control/ref/sway"
          heave: "/#vehicle#/control/ref/heave"
          roll: "/#vehicle#/control/ref/roll"
          roll_rate: "/#vehicle#/control/ref/roll_rate"
          pitch: "/#vehicle#/control/ref/pitch"
          pitch_rate: "/#vehicle#/control/ref/pitch_rate"
          yaw: "/#vehicle#/control/ref/yaw"
          yaw_rate: "/#vehicle#/control/ref/yaw_rate"
          # Publishers for the virtual target
          rabbit: "/#vehicle#/control/outer_loop/gamma"
          # Observer for the currents
          observer:
            x: "/#vehicle#/current/x"
            y: "/#vehicle#/current/y"
          # Publish info for plots
          pfollowing_debug: "/#vehicle#/control/outer_loop/path_following/debug"
        services:
          # Service names to start and stop the path following algorithm
          start_pf: "/#vehicle#/control/outer_loop/path_following/Start"
          stop_pf: "/#vehicle#/control/outer_loop/path_following/Stop"
          updates_gains_pf: "/#vehicle#/control/outer_loop/path_following/UpdateGains"
          reset_vt_pf: "/#vehicle#/ResetVT"
          # Service names to switch the path following algorithm
          relative_heading_pf: "/#vehicle#/control/outer_loop/path_following/SetRelativeHeading"
          marcelo_pf: "/#vehicle#/control/outer_loop/path_following/SetMarcelo"
          aguiar_pf: "/#vehicle#/control/outer_loop/path_following/SetAguiar"
          breivik_pf: "/#vehicle#/control/outer_loop/path_following/SetBrevik"
          fossen_pf: "/#vehicle#/control/outer_loop/path_following/SetFossen"
          romulo_pf: "/#vehicle#/control/outer_loop/path_following/SetRomulo"
          lapierre_pf: "/#vehicle#/control/outer_loop/path_following/SetLapierre"
          pramod_pf: "/#vehicle#/control/outer_loop/path_following/SetPramod"
          samson_pf: "/#vehicle#/control/outer_loop/path_following/SetSamson"
          # Service names related to the path
          reset_path: "/#vehicle#/ResetPath"
          set_path_mode: "/#vehicle#/SetMode"
          # Service names related to the waypoint
          wp_standard: "/#vehicle#/control/outer_loop/send_wp_standard"
          # Service for resetting Dead Reckoning in filter
          reset_dr: "/#vehicle#/nav/filter/reset_dead_reckoning"

######################
# ---  Planning  --- #
######################
  paths:
    ros__parameters:
      topics:
        subscribers:
          gamma: "/#vehicle#/control/outer_loop/gamma"
          vehicle_state: "/#vehicle#/nav/filter/state"
        publishers:
          path_data: "/#vehicle#/control/outer_loop/path_data"
          virtual_target_state: "/#vehicle#/control/outer_loop/virtual_state"
        services: # Services for constructing a path
          reset_path: "/#vehicle#/ResetPath"
          set_mode: "/#vehicle#/SetMode"
          arc2d_path: "/#vehicle#/SpawnArc2DPath"
          bernoulli_path: "/#vehicle#/SpawnBernoulliPath"
          circle2d_path: "/#vehicle#/SpawnCircle2DPath"
          line_path: "/#vehicle#/SpawnLinePath"
          speed:
            const_rabbit_speed: "/#vehicle#/SetConstVdRabbit"
            const_vehicle_speed: "/#vehicle#/SetConstVdVehicle"

####################
# ---  Addons  --- #
####################
  console_parser:
    ros__parameters:
      topics:
        subscribers: 
          Mission_String: "/#vehicle#/addons/Mission_String"
          state: "/#vehicle#/nav/filter/state"
          mission_status: "/#vehicle#/mission_status"
        publishers:
          Path_Section: "/#vehicle#/addons/path_section"
          Formation: "/#vehicle#/addons/formation"
          biased_formation: "/#vehicle#/addons/biased_formation"
          WPRef: "/#vehicle#/addons/WPRef"
          DepthRef: "/#vehicle#/control/ref/depth"
          AltRef: "/#vehicle#/control/ref/altitude"
          FullMission: "/#vehicle#/addons/full_mission"
        services:
          reset_path: "/#vehicle#/ResetPath"
          arc2d_path: "/#vehicle#/SpawnArc2DPath"
          line_path: "/#vehicle#/SpawnLinePath"
          pf_start: "/#vehicle#/control/outer_loop/path_following/Start"
          pf_stop: "/#vehicle#/control/outer_loop/path_following/Stop"
          set_speed: "/#vehicle#/SetConstVdVehicle"
  console_server:
    ros__parameters:
      topics:
        services:
          wp_standard: "/#vehicle#/control/outer_loop/send_wp_standard"
          wp_loose: "/#vehicle#/control/outer_loop/send_wp_loose"
          wp_heading: "/#vehicle#/control/outer_loop/send_wp_heading"
        console:
          waypoint: "wp_standard"
  nav2console_state:
    ros__parameters:
      topics:
        subscribers:
          nav_state: "/#vehicle#/nav/filter/state"
        publishers:
          console_state: "/#vehicle#/State"

########################
# ---  Simulation  --- #
########################
  simulation:
    ros__parameters:
      topics:
        subscribers:
          thruster_force: "/#vehicle#/actuation/thruster_force"
        publishers:
          position: "/#vehicle#/sim/position"
          orientation: "/#vehicle#/sim/orientation"
          velocity: "/#vehicle#/sim/velocity"
          angular_velocity: "/#vehicle#/sim/angular_velocity"

