/**:
  ros__parameters:
    actuation:
      rpm_conversion:
        node_frequency: 10
        topics:
          subscribers:
            thruster_force: "/#vehicle#/actuation/thruster_force"
          publishers:
            rpm_command: "/#vehicle#/actuation/rpm_command"
      static_thruster_allocation:
        node_frequency: 10
        topics:
          subscribers:
            body_wrench_request: "/#vehicle#/actuation/body_wrench_request"
          publishers:
            thruster_force: "/#vehicle#/actuation/thruster_force"
      thruster_rudder_allocation:
        node_frequency: 1
        topics:
          subscribers:
            body_wrench_request: "/#vehicle#/actuation/body_wrench_request"
            nav_state: "/#vehicle#/nav/filter/state"
          publishers:
            thruster_force: "/#vehicle#/actuation/thruster_force"
            rudder_angle_ref: "/#vehicle#/control/ref/rudder_angle"
      wrench_manager:
        node_frequency: 10
        topics:
          subscribers:
            thrust_x: "/#vehicle#/actuation/thrust_x"
            thrust_y: "/#vehicle#/actuation/thrust_y"
            thrust_z: "/#vehicle#/actuation/thrust_z"
            torque_x: "/#vehicle#/actuation/torque_x"
            torque_y: "/#vehicle#/actuation/torque_y"
            torque_z: "/#vehicle#/actuation/torque_z"
          publishers:
            body_wrench_request: "/#vehicle#/actuation/body_wrench_request"
    addons:
      console_parser:
        node_frequency: 5
        topics:
          subscribers: 
            Mission_String: "/#vehicle#/addons/Mission_String"
            state: "/#vehicle#/nav/filter/state"
            mission_status: "/#vehicle#/mission_status"
          publishers:
            Path_Section: "/#vehicle#/addons/path_section"
            Formation: "/#vehicle#/addons/formation"
            biased_formation: "/#vehicle#/addons/biased_formation"
            WPRef: "/#vehicle#/addons/WPRef"
            DepthRef: "/#vehicle#/control/ref/depth"
            AltRef: "/#vehicle#/control/ref/altitude"
            FullMission: "/#vehicle#/addons/full_mission"
          services:
            reset_path: "/#vehicle#/ResetPath"
            arc2d_path: "/#vehicle#/SpawnArc2DPath"
            line_path: "/#vehicle#/SpawnLinePath"
            pf_start: "/#vehicle#/control/outer_loop/path_following/Start"
            pf_stop: "/#vehicle#/control/outer_loop/path_following/Stop"
            set_speed: "/#vehicle#/SetConstVdVehicle"
      console_server:
        topics:
          services:
            wp_standard: "/#vehicle#/control/outer_loop/send_wp_standard"
            wp_loose: "/#vehicle#/control/outer_loop/send_wp_loose"
            wp_heading: "/#vehicle#/control/outer_loop/send_wp_heading"
          console:
            waypoint: "wp_standard"
      nav2console_state:
        topics:
          subscribers:
            nav_state: "/#vehicle#/nav/filter/state"
          publishers:
            console_state: "/#vehicle#/State"
    control:
      inner_loop:
        pid:
          node_frequency: 10
          topics:
            subscribers:
              nav_state: "/#vehicle#/nav/filter/state"
              surge_ref: "/#vehicle#/control/ref/surge"
              sway_ref: "/#vehicle#/control/ref/sway"
              heave_ref: "/#vehicle#/control/ref/heave"
              yaw_ref: "/#vehicle#/control/ref/yaw"
              pitch_ref: "/#vehicle#/control/ref/pitch"
              roll_ref: "/#vehicle#/control/ref/roll"
              yaw_rate_ref: "/#vehicle#/control/ref/yaw_rate"
              pitch_rate_ref: "/#vehicle#/control/ref/pitch_rate"
              roll_rate_ref: "/#vehicle#/control/ref/roll_rate"
            publishers:
              thrust_x: "/#vehicle#/actuation/thrust_x"
              thrust_y: "/#vehicle#/actuation/thrust_y"
              thrust_z: "/#vehicle#/actuation/thrust_z"
              torque_x: "/#vehicle#/actuation/torque_x"
              torque_y: "/#vehicle#/actuation/torque_y"
              torque_z: "/#vehicle#/actuation/torque_z"
            services:
              change_params: "/#vehicle#/control/pid/change_params"
        open_loop:
          node_frequency: 10
          topics:
            subscribers:
              surge_ref: "/#vehicle#/control/ref/surge"
            publishers:
              thrust_x: "/#vehicle#/actuation/thrust_x"
              # thrust_y: "/#vehicle#/actuation/thrust_y"
              # thrust_z: "/#vehicle#/actuation/thrust_z"
              # torque_x: "/#vehicle#/actuation/torque_x"
              # torque_y: "/#vehicle#/actuation/torque_y"
              # torque_z: "/#vehicle#/actuation/torque_z"
      outer_loop:
        waypoint:
          node_frequency: 10
          topics:
            subscribers:
              mission_status: "/#vehicle#/mission_status"
              state: "/#vehicle#/nav/filter/state"
              turn_radius_flag: "/#vehicle#/turn_radius_flag"
            publishers:
              yaw_ref: "/#vehicle#/control/ref/yaw"
              yaw_rate_ref: "/#vehicle#/control/ref/yaw_rate"
              u_ref: "/#vehicle#/control/ref/surge"
              v_ref: "/#vehicle#/control/ref/sway"
              mission_status: "/#vehicle#/mission_status"
            services:
              wp_standard: "/#vehicle#/control/outer_loop/send_wp_standard"
              wp_loose: "/#vehicle#/control/outer_loop/send_wp_loose"
              wp_heading: "/#vehicle#/control/outer_loop/send_wp_heading"
        path_following:
          node_frequency: 10
          topics:
            subscribers:
              mission_status: "/#vehicle#/mission_status"
              state: "/#vehicle#/nav/filter/state"
              path_data: "/#vehicle#/control/outer_loop/path_data"
              vc: "/#vehicle#/control/outer_loop/path_following/vc"
            publishers:
              mission_status: "/#vehicle#/mission_status"
              surge: "/#vehicle#/control/ref/surge"
              sway: "/#vehicle#/control/ref/sway"
              heave: "/#vehicle#/control/ref/heave"
              roll: "/#vehicle#/control/ref/roll"
              roll_rate: "/#vehicle#/control/ref/roll_rate"
              pitch: "/#vehicle#/control/ref/pitch"
              pitch_rate: "/#vehicle#/control/ref/pitch_rate"
              yaw: "/#vehicle#/control/ref/yaw"
              yaw_rate: "/#vehicle#/control/ref/yaw_rate"
              # Publishers for the virtual target
              rabbit: "/#vehicle#/control/outer_loop/gamma"
              # Observer for the currents
              observer:
                x: "/#vehicle#/current/x"
                y: "/#vehicle#/current/y"
              # Publish info for plots
              pfollowing_debug: "/#vehicle#/control/outer_loop/path_following/debug"
            services:
              # Service names to start and stop the path following algorithm
              start_pf: "/#vehicle#/control/outer_loop/path_following/Start"
              stop_pf: "/#vehicle#/control/outer_loop/path_following/Stop"
              updates_gains_pf: "/#vehicle#/control/outer_loop/path_following/UpdateGains"
              reset_vt_pf: "/#vehicle#/ResetVT"
              # Service names to switch the path following algorithm
              relative_heading_pf: "/#vehicle#/control/outer_loop/path_following/SetRelativeHeading"
              marcelo_pf: "/#vehicle#/control/outer_loop/path_following/SetMarcelo"
              aguiar_pf: "/#vehicle#/control/outer_loop/path_following/SetAguiar"
              breivik_pf: "/#vehicle#/control/outer_loop/path_following/SetBrevik"
              fossen_pf: "/#vehicle#/control/outer_loop/path_following/SetFossen"
              romulo_pf: "/#vehicle#/control/outer_loop/path_following/SetRomulo"
              lapierre_pf: "/#vehicle#/control/outer_loop/path_following/SetLapierre"
              pramod_pf: "/#vehicle#/control/outer_loop/path_following/SetPramod"
              samson_pf: "/#vehicle#/control/outer_loop/path_following/SetSamson"
              # Service names related to the path
              reset_path: "/#vehicle#/ResetPath"
              set_path_mode: "/#vehicle#/SetMode"
              # Service names related to the waypoint
              wp_standard: "/#vehicle#/control/outer_loop/send_wp_standard"
              # Service for resetting Dead Reckoning in filter
              reset_dr: "/#vehicle#/nav/filter/reset_dead_reckoning"
    nav:
      filter_handler:
        node_frequency: 10
        topics:
          subscribers:
            sample_and_hold: "/#vehicle#/nav/sample_and_hold/state"
            complementary: "/#vehicle#/nav/complementary/state"
          publishers:
            state: "/#vehicle#/nav/filter/state"
          services:
            change_filter: "/#vehicle#/nav/change_filter"
      sample_and_hold:
        node_frequency: 10
        topics:
          subscribers:
            measurement: "/#vehicle#/measurement"
          publishers:
            state: "/#vehicle#/nav/sample_and_hold/state"
    sim:
      simulation:
        node_frequency: 10
        topics:
          subscribers:
            test0: "/#vehicle#/sim/something"
          publishers:
            test1: "/#vehicle#/sim/something_else"
          services:
            test2: "/#vehicle#/sim/change_something"
    planning:
      paths:
        node_frequency: 10
        topics:
          subscribers:
            gamma: "/#vehicle#/control/outer_loop/gamma"
            vehicle_state: "/#vehicle#/nav/filter/state"
          publishers:
            path_data: "/#vehicle#/control/outer_loop/path_data"
            virtual_target_state: "/#vehicle#/control/outer_loop/virtual_state"
          services: # Services for constructing a path
            reset_path: "/#vehicle#/ResetPath"
            set_mode: "/#vehicle#/SetMode"
            arc2d_path: "/#vehicle#/SpawnArc2DPath"
            bernoulli_path: "/#vehicle#/SpawnBernoulliPath"
            circle2d_path: "/#vehicle#/SpawnCircle2DPath"
            line_path: "/#vehicle#/SpawnLinePath"
            speed:
              const_rabbit_speed: "/#vehicle#/SetConstVdRabbit"
              const_vehicle_speed: "/#vehicle#/SetConstVdVehicle"
    drivers:
      can_thrusters:
        topics:
          subscribers:
            throttle_command: "/#vehicle#/throttle_command"
            mission_status: "/#vehicle#/mission_status"
          publishers:
            port:
              can_raw: "/#vehicle#/drivers/can_thrusters/port/can_raw"
              throttle_status0: "/#vehicle#/drivers/can_thrusters/port/throttle_status0"
              motor_controller_status0: "/#vehicle#/drivers/can_thrusters/port/motor_controller_status0"
              motor_controller_status1: "/#vehicle#/drivers/can_thrusters/port/motor_controller_status1"
            stbd:
              can_raw: "/#vehicle#/drivers/can_thrusters/stbd/can_raw"
              throttle_status0: "/#vehicle#/drivers/can_thrusters/stbd/throttle_status0"
              motor_controller_status0: "/#vehicle#/drivers/can_thrusters/stbd/motor_controller_status0"
              motor_controller_status1: "/#vehicle#/drivers/can_thrusters/stbd/motor_controller_status1"
      can_instrumentation:
        topics:
          subscribers:
            rudder_command: "/#vehicle#/rudder_command"
          publishers:
            position: "/#vehicle#/drivers/can_instrumentation/position"
            orientation: "/#vehicle#/drivers/can_instrumentation/orientation"
            can_raw: "/#vehicle#/drivers/can_instrumentation/can_raw"
            rudder_angle: "/#vehicle#/drivers/can_instrumentation/rudder_angle"
            measurement: "/#vehicle#/measurement"
      vn310:
        node_frequency: 10
        topics:
          publishers:
            raw: /#vehicle#/drivers/vn310/raw 
            vnins_data: /#vehicle#/drivers/vn310/VNINS/data
            measurement: /#vehicle#/measurement
            vn_gnss_lla: /#vehicle#/drivers/vn310/GPSLLA/data
            vn_ymr: /#vehicle#/drivers/vn310/YMR/data
            vn_gnss_health_status: /#vehicle#/drivers/vn310/GPSHealthStatus/data
            vn_gpgga: /#vehicle#/drivers/vn310/GPGGA/data
            corrections_rtk: /#vehicle#/drivers/vn310/corrections_rtk
      airmar200wx:
        topics:
          publishers:
            raw: /#vehicle#/drivers/airmar200wx/raw
            true_heading: /#vehicle#/drivers/airmar200wx/true_heading
            wind_true: /#vehicle#/drivers/airmar200wx/wind_true
            wind_rel: /#vehicle#/drivers/airmar200wx/wind_apparent
            gps_fix: /#vehicle#/drivers/airmar200wx/gps_fix
            ground_speed: /#vehicle#/drivers/airmar200wx/ground_speed
            rate_of_turn: /#vehicle#/drivers/airmar200wx/rate_of_turn
            transducers: /#vehicle#/drivers/airmar200wx/transducers
            meteo_composite: /#vehicle#/drivers/airmar200wx/meteo_composite
            time_date: /#vehicle#/drivers/airmar200wx/time_date
      airmardx900:
        topics:
          publishers:
            raw: /#vehicle#/drivers/airmardx900/raw
            nautical_leeway_angle: /#vehicle#/drivers/airmardx900/nautical_leeway_angle
            ground_water_speed: /#vehicle#/drivers/airmardx900/ground_water_speed
            speed_through_water: /#vehicle#/drivers/airmardx900/speed_through_water
            distance_through_water: /#vehicle#/drivers/airmardx900/distance_through_water
            sea_water_temperature: /#vehicle#/drivers/airmardx900/sea_water_temperature
            transducers: /#vehicle#/drivers/airmardx900/transducers