/**:
  auv_sim:
    ros__parameters:
      node_frequency: 100
      speedup: 20.0
      initial_state:
        position: [38.690323, -9.211736, 0.0] # (lat, lon, depth) from expo   
        body_velocity: [0.0, 0.0, 0.0]
        orientation: [0.0, 0.0, 0.0]
        orientation_rate: [0.0, 0.0, 0.0]
      environment:
        fluid_density: 1.025 # (kg/l)
        current:
          mean: [0.0, 0.0, 0.0]
          sigma: [0.0, 0.0, 0.0]
          minimum: [0.0, 0.0, 0.0]
          maximum: [0.0, 0.0, 0.0]
      vehicle:
        mass: 10.5 # (kg)
        zg: 0.0 # center of gravity in body axis (m)
        vehicle_density: 1.0 # TO DEFINE LATER
        inertia_tensor: [1000.0, 1000.0, 4.14]  # diagonal (3x3) moment of inertia matrix (kg/m2)
        linear_damping_tensor: [-0.1213, -1.1732, -1.1130, -0.5, -0.5, -0.5] # diagonal (6x6) matrix with linear damping
        quadratic_damping_tensor: [-23.9, -46.27, -50.278,  -1.0, -1.0, -1.0] # diagonal (6x6) matrix with quadratic damping
        added_mass_tensor: [27.08, 25.952, 29.9081, 1.0, 1.0, 1.0] # diagonal (6x6) matrix with added mass terms

        actuators:
          # For each thruster [Fx, Fy, Fz, lx, ly, lz] where F = forces and l = moments arms
          # and each line of the matrix represents a thruster
      allocation_matrix: [0.707, -0.707,  0.0,  0.1355,     0.1, 0.0725,     # Thruster 1
                        0.707,  0.707,  0.0,  0.1355,    -0.1, 0.0725,     # Thruster 2
                       -0.707, -0.707,  0.0, -0.1475,     0.1, 0.0725,     # Thruster 3
                       -0.707,  0.707,  0.0, -0.1475,    -0.1, 0.0725,     # Thruster 4
                        0.000,  0.000, -1.0,  0.1200,    0.22,  0.005,     # Thruster 5
                        0.000,  0.000, -1.0,  0.1200,   -0.22,  0.005,     # Thruster 6
                        0.000,  0.000, -1.0, -0.1200,    0.22,  0.005,     # Thruster 7
                        0.000,  0.000, -1.0, -0.1200,   -0.22,  0.005]     # Thruster 8

          # Thrusters parameter
          lump_param_positive: [0.00000177778, 0.0, 0.0]  # (a*|x|^{2} + b*|x| + c)
          lump_param_negative: [-0.00000177778, 0.0, 0.0] # (a*|x|^{2} + b*|x| + c)

          max_input: 5000.0 # Maximum RPM input value
          min_input: 430.0 # Minimum RPM input value (for values < |min_input|) the motors "won't" spin <-> dead-zone
          min_max_thruster_input: [430.0, 5000.0] # Minimum and maximum RPM values for thrusters

          # Model of each thruster is the same as for a regular DC motor (pole+delay)
          pole: 7.2115
          delay: 0.345 # 0.345s
          period: 0.01
      sensor:
        gnss: true
        depth_sensor: true
        imu: true
        noise:
          activate: false
          position:
            bias: [0.0, 0.0, 0.0] #Northing, Easting, Depth
            variance: [0.0, 0.0, 0.0] #Northing, Easting, Depth
          body_velocity:
            bias: [0.0, 0.0, 0.0] # North, East, Down inertial velocity
            variance: [0.0, 0.0, 0.0] # North, East, Down inertial velocity
          fluid_velocity:
            bias: [0.0, 0.0, 0.0] # Surge, Sway, Heave relative to water
            variance: [0.0, 0.0, 0.0] # Surge, Sway, Heave relative to water
          orientation:
            bias: [0.0, 0.0, 0.0] # Roll, Pitch, Yaw
            variance: [0.0, 0.0, 0.0] # Roll, Pitch, Yaw
          orientation_rate:
            bias: [0.0, 0.0, 0.0] # Roll rate, Pitch rate, Yaw rate
            variance: [0.0, 0.0, 0.0] # Roll rate, Pitch rate, Y


                
