/**:
  ros__parameters:
    control:
      inner_loop:
        pid:
          # Speeds (surge, sway, heave)
          surge:
            enabled: true
            kp: 10.0
            ki: 1.0
            lpf_pole: 31.4 # rad/s
            tau_min: -30.0 # N
            tau_max: 30.0 # N
          sway:
            enabled: false
            kp: 1.0
            ki: 1.0
            lpf_pole: 31.4 # rad/s
            tau_min: -20.0 # N
            tau_max: 20.0 # N
          heave:
            enabled: false
            kp: 1.0
            ki: 1.0
            lpf_pole: 31.4 # rad/s
            tau_min: -20.0 # N
            tau_max: 20.0 # N
          # Angles (yaw, pitch, roll)
          yaw:
            enabled: true
            kp: 1.0
            ki: 1.0
            kd: 1.0
            lpf_pole: 31.4 # rad/s
            tau_min: -10.0 # N.m
            tau_max: 10.0 # N.m
          pitch:
            enabled: false
            kp: 1.0
            ki: 1.0
            kd: 1.0
            lpf_pole: 31.4 # rad/s
            tau_min: -10.0 # N.m
            tau_max: 10.0 # N.m
          roll:
            enabled: false
            kp: 1.0
            ki: 1.0
            kd: 1.0
            lpf_pole: 31.4 # rad/s
            tau_min: -10.0 # N.m
            tau_max: 10.0 # N.m
          # Angle rates (yaw rate, pitch rate, roll rate)
          yaw_rate:
            enabled: false
            kp: 1.0
            ki: 1.0
            lpf_pole: 31.4 # rad/s
            tau_min: -10.0 # N.m
            tau_max: 10.0 # N.m
          pitch_rate:
            enabled: false
            kp: 1.0
            ki: 1.0
            lpf_pole: 31.4 # rad/s
            tau_min: -10.0 # N.m
            tau_max: 10.0 # N.m
          roll_rate:
            enabled: false
            kp: 1.0
            ki: 1.0
            lpf_pole: 31.4 # rad/s
            tau_min: -10.0 # N
            tau_max: 10.0 # N-m
          # Full attitude (yaw, pitch and roll)
          attitude:
            enabled: false
        open_loop:
          # Speeds (surge)
          surge:
            enabled: true
            gain: 100.0
      outer_loop:
        waypoint:
          cdist: 1.5
          delta_t: 5.0
          type1:
            gains:
                ku: 1.0
                ks: 4.0
                speed_turn: 5.0
          type2:
            gains:
              k1: 0.05
              k2: 0.1
              k3: 0.1
        # Path Following configurations
        # Be careful while changing values here, due to the way the PF code is implemented,
        # the order of the following gains must be respected. This means you can't switch
        # the lines k1 and k2 in lapierre, for example.
        path_following:
          controller_gains:
            lapierre:
              k1: 1.0
              k2: 0.3
              k3: 0.3
              theta: 0.8
              k_delta: 1.0
            aguiar:
              delta: -1.0
              kx: 0.8
              ky: 0.8
              kz: 0.5
              k_pos: 0.5
              k_currents: 0.5
            marcelo:
              delta: -1.0
              kx: 0.5
              ky: 0.5
              kz: 0.5
              k_pos: 2.0
              k_currents: 0.2
              rd: [0.0, 0.0, 1.0]
              d: [-5.0, 5.0, 0.0]
            romulo:
              ke: [0.05, 0.0, 0.0, 0.05]
              kz: 0.2
            pramod:
              kp: 0.14
              ki: 0.01
            samson:
              k1: 1.0
              k2: 0.3
              k3: 0.3
              theta: 0.8
              k_delta: 1.0
            relative_heading:
              kx: 0.05
              ky: 0.05
              kz: 0.2
              yaw_offset: 0.0
              p_sat: [10.0, 10.0] #x, y
            breivik:
              delta_h: 2.0