################################
#  Parameters
################################
# "/**" is needed for nodes to find their params despite the "/vehicle0/<meta_package>/"<node_name>. the /**/ essentially leaves only the "node_name" as a key.
/**:
  filter_node:
    ros__parameters:
      node_frequency: 10.0
      publish_all_steps: true

      filters: 
        - "" 
      measurements:
        - "gnss"
        - "imu"
        - "altimeter"
        - "thruster_rpm"
      
      # plugins:
        