<?xml version="1.0"?>
<package format="3">
  <name>vehicle_sim</name>
  <version>0.0.0</version>
  <description>Vehicle simulation nodes</description>

  <maintainer email="andre.jose.diniz.carvalho@tecnico.ulisboa.pt">
    André Carvalho
  </maintainer>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Dependencies -->
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>farol_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>rosgraph_msgs</depend>
  <depend>control_allocation</depend>

  <exec_depend>ros2launch</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
