################################
#   Default Parameters
################################

/**:
  wrench_manager:
    ros__parameters:
      node_frequency: 10.0

  thruster_allocation:
    ros__parameters:
      node_frequency: 10.0
      allocation:
        type: "thrust_rudder"
        model:
          K_s: 1.0
          K_L: 0.0    # 0.0 -> drag induced by rudder is not accounted for
          K_D0: 0.0   # 0.0 -> drag induced by rudder is not accounted for
          K_D1: 0.0   # 0.0 -> drag induced by rudder is not accounted for
        rudder:
          limits:
            max: 30.0 # [deg]
            min: -30.0 # [deg]
          cm_distance: 4.0 # [m]
        thrusters:
          open_loop: true
          base_frame: "base_link"
          thrust_axis: [1.0, 0.0, 0.0]
          frames:
            - "thruster_middle_link"
  
  rpm_conversion:
    ros__parameters:
      allocation_type: "thruster_rudder_allocation"
      mode: 0 #Mode 1 uses coef_fwd and coef_bwd, mode 0 uses rho, K_T_BP, prop_pitch and D
      # Force [N] = rho*(rpm/60)^2*D^4*K_T_BP*(1 - u/(rps*prop_pitch))
      rho: 1025.0 # % Density of salt water kg/m^3
      K_T_BP: 0.061461915
      prop_pitch: 0.381 # 15 in
      D: 0.4318 # m
      # Forces (N) = ct[0]*RPM^2 + c[1]*RPM + c[2]
      coef_fwd: [0.00000177778, 0.0, 0.0]     # parameters for farol seabotix, eqn -> Thrust = f(rpm)
      coef_bwd: [-0.00000177778, 0.0, 0.0]    # parameters for farol seabotix, eqn -> Thrust = f(rpm)
      max_rpm: 2000.0
      min_rpm: -2000.0

