################################
#   Override Parameters
################################
/**:
  inner_loop:
    ros__parameters:
      node_frequency: 10.0
      ref_timeout: 2.0 # seconds before resetting reference generator to current state
      course_instead_of_yaw: false   # set to true to control course angle instead of yaw
      lpf_order: 3
      lpf_method: "tustin"
      lpf_design: "bessel"
      
###########
#   YAW   #
###########
      ## Delta pid implementation
      # yaw:
      #   debug: true
      #   enabled: true
      #   delta_implementation: true
      #   use_ref_lpf: true
      #   use_rate_limiter: true
      #   rate_limit: 4.0 # deg/s
      #   kp: 21.0
      #   ki: 2.0
      #   kd: 110.0
      #   kffv_lin: 14.334052 # linear drag term (N.s/m) SHOULD BE POSITIVE
      #   kffv_sq: 260.675031 # quadratic drag term (N.s^2/m^2) SHOULD BE POSITIVE
      #   # kffa: 88.478840   # hydrodynamic compensated mass (Kg) SHOULD BE POSITIVE
      #   # kffv_lin: 0.0
      #   # kffv_sq: 0.0
      #   kffa: 0.0
      #   lpf_wc: 1.0 # 6.28 # rad/s (2hz about the maximum possible given that sampling is 10hz)
      #   # lpf_wc: 12.5664 # rad/s (2hz about the maximum possible given that sampling is 10hz)
      #   tau_min: -6.0  # N.m (actual in simulation is 5.93)
      #   tau_max: 6.0 # N.m

      ## Simple pid
      yaw:
        debug: true
        enabled: true
        delta_implementation: false
        use_ref_lpf: true
        use_rate_limiter: true
        rate_limit: 4.0 # deg/s
        kp: 9.504000 
        ki: 0.616000 
        kd: 73.920000
        kffv_lin: 0.0
        kffv_sq: 0.0
        kffa: 0.0
        lpf_wc: 2.0 # rad/s  ( 12.5664 rad/s = 2hz about the maximum possible given that sampling is 10hz)
        tau_min: -6.0  # N.m (actual in simulation is 5.93)
        tau_max: 6.0 # N.m


#############
#   SURGE   #
#############
      surge:
        enabled: false
        kp: 10.0
        ki: 1.0
        lpf_wc: 31.4 # rad/s
        tau_min: -30.0 # N
        tau_max: 30.0 # N

################
#   YAW RATE   #
################
      yaw_rate:
        enabled: false
        kp: 1.0
        ki: 1.0
        lpf_wc: 31.4 # rad/s
        tau_min: -10.0 # N.m
        tau_max: 10.0 # N.m

  open_loop:
    ros__parameters:
      surge:
        enabled: true
        gain: 2200.0 # surge m/s to rpms (basically max_rpms)
