################################
#  Parameters
################################

# "/**" is needed for nodes to find their params despite the "/vehicle0/<meta_package>/"<node_name>. the /**/ essentially leaves only the "node_name" as a key.
/**:
  filter_node:
    ros__parameters:
      node_frequency: 10.0
      publish_all_steps: true
      
      measurements:
        gnss: true
        imu: true
        utm_ned: false
        velocity_over_ground: false
        velocity_through_water: false
        depth: false
        altimeter: false
        rudder_angle: true
        rpm_command: true
      
      filters: 
        - "position_current_ekf"
        - "yaw_rate_ekf"
        - "asv_dynamics_model"
      
      plugins:
        position_current_ekf:
          override_position_state: false
          process_noise_pos: 0.1
          process_noise_current: 0.01
          measurement_noise_pos: 10000.0
          init_cov_pos: 25.0
          init_cov_current: 1.0
          init_current_x: 0.0
          init_current_y: 0.0
          rpm_min: -2000.0
          rpm_max: 2000.0
          rpm_rate_limit: 200.0
          rho: 1025.0
          prop_pitch: 0.381
          prop_diameter: 0.4318
          k_t_bp: 0.061461915
          m_u: 3100.0
          x_u: 0.0
          x_uu: -96.2270

        yaw_rate_ekf:
          process_noise_yaw_rate: 0.02
          process_noise_bias: 0.01
          # measurement_noise_yaw_rate: 0.1
          measurement_noise_yaw_rate: 100000000.0
          measurement_window_samples: 30 
          init_cov_yaw_rate: 1.0
          init_cov_bias: 1.0
          inertia: 88.478840
          damping: 14.334052
          # damping: 28.0
          damping_quadratic: 260.675031
          torque_gain: 1.0
          K_L: 1.398093 
          K_D0: 0.000575
          K_D1: 0.520834
          rudder_arm: 4.0

        asv_dynamics_model:
          rpm_min: -2000.0
          rpm_max: 2000.0
          rpm_rate_limit: 200.0
          rho: 1025.0
          prop_pitch: 0.381
          prop_diameter: 0.4318
          k_t_bp: 0.061461915
          m_u: 3100.0
          m_uv: -2.967651
          x_u: 0.0
          x_uu: -96.2270
          Y_v: -500.0
          Y_vv: -1500.0
          m_r: 88.478840
          damping: 14.334052
          damping_quadratic: 260.675031
          rudder_arm: 4.0
          rudder_angle_limit_deg: 36.0
          K_L: 1.398093
          K_D0: 0.000575
          K_D1: 0.520834
          torque_bias: 0.0
          init_u: 0.0
          init_v: 0.0
          init_r: 0.0
