################################
#   Parameters
################################
/**:
  # Path Following configurations
  # Be careful while changing values here, due to the way the PF code is implemented,
  # the order of the following gains must be respected. This means you can't switch
  # the lines k1 and k2 in lapierre, for example.
  path_following:
    ros__parameters:
      node_frequency: 10.0
      default_algorithm: ravi
      controller_gains:
        ravi:
          e_turn: 45.0            # meters at which to start turning, equivalent to lookahead distance
          min_corridor: 45.0      # minimum hlaf-width of inner corridor where integral action is applied
          xi: 1.0                 # ξ of the final system with integral
          w0_min: 0.08            # ω0 of the final system with integral
          epsilon_current: 0.2    # confidence on current estimate 
        
        pramod:
          kp: 0.14
          ki: 0.01

        breivik:
          delta_h: 10.0
        
        ilos:
          delta: 10.0  # lookahead distance (metres)
          ki: 0.05     # integral gain
