<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>farol_description</name>
  <version>0.0.1</version>
  <description>URDF descriptions for dsor vessels</description>

   <maintainer email="ravi.regalo@tecnico.ulisboa.pt">Ravi Regalo</maintainer>
   <license>TODO</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>