################################
#  Parameters
################################
/**:
  filter_node:
    ros__parameters:
      node_frequency: 10.0
      publish_all_steps: true

      filters: 
        - ""
      
      measurements:
        - "gnss"
        - "imu"
        - "velocity_over_ground"
        - "velocity_through_water"
        - "depth"
        - "altimeter"
        - "thruster_rpm"
      
      plugins:
        sample_and_hold:
          initializer_measurements:
            - "gnss"
            - "imu"
