/**:
  sim_clock:
    ros__parameters:
      node_frequency: 100 #Must be the largest frequency in the system
      speedup: 1.0
  auv_sim:
    ros__parameters:
      node_frequency: 100
      initial_state:
        position: [38.690323, -9.211736, 0.0] # (lat, lon, depth) from expo   
        body_velocity: [0.0, 0.0, 0.0]
        orientation: [0.0, 0.0, 0.0]
        orientation_rate: [0.0, 0.0, 0.0]
      environment:
        fluid_density: 1.025 # (kg/l)
        current:
          mean: [0.0, 0.0, 0.0]
          sigma: [0.0, 0.0, 0.0]
          minimum: [0.0, 0.0, 0.0]
          maximum: [0.0, 0.0, 0.0]
      vehicle:
        mass: 30.0 # (kg)
        zg: 0.0 # center of gravity in body axis (m)
        vehicle_density: 1.0 # TO DEFINE LATER
        inertia_tensor: [1000.0, 1000.0, 4.14]  # diagonal (3x3) moment of inertia matrix (kg/m2)
        linear_damping_tensor: [0.0, -55.1, -4.1879, -3000.0, -3000.0, -4.14] # diagonal (6x6) matrix with linear damping
        quadratic_damping_tensor: [-27.5, -101.0, -40.9649,  -3000.0, -3000.0, -6.23] # diagonal (6x6) matrix with quadratic damping
        added_mass_tensor: [20.0, 30.0, 80.088, 0.0, 0.0, 0.5] # diagonal (6x6) matrix with added mass terms

        actuators:
          base_frame: "base_link"
          frames:
            - "thruster_portside_horizontal_back_link"
            - "thruster_starboard_horizontal_back_link"
            - "thruster_starboard_vertical_link"
            - "thruster_portside_vertical_link"
            - "thruster_portside_horizontal_front_link"
            - "thruster_starboard_horizontal_front_link"

          # Thrusters parameter
          lump_param_positive: [0.00000177778, 0.0, 0.0]  # (a*|x|^{2} + b*|x| + c)
          lump_param_negative: [-0.00000177778, 0.0, 0.0] # (a*|x|^{2} + b*|x| + c)

          min_max_thruster_input: [430.0, 5000.0] # Minimum and maximum RPM values for thrusters

          # Model of each thruster is the same as for a regular DC motor (pole+delay)
          pole: 7.2115
          delay: 0.345 # 0.345s
          period: 0.01
      sensor:
        gnss: true
        gnss_velocity_over_ground: true
        depth_sensor: true
        imu: true
        dvl_activate: false
        dvl:
          mode: "bottom_track"
          output_frame: "body"
        noise:
          activate: false
          position:
            bias: [0.0, 0.0, 0.0] #Northing, Easting, Depth
            variance: [0.0, 0.0, 0.0] #Northing, Easting, Depth
          body_velocity:
            bias: [0.0, 0.0, 0.0] # North, East, Down inertial velocity
            variance: [0.0, 0.0, 0.0] # North, East, Down inertial velocity
          fluid_velocity:
            bias: [0.0, 0.0, 0.0] # Surge, Sway, Heave relative to water
            variance: [0.0, 0.0, 0.0] # Surge, Sway, Heave relative to water
          orientation:
            bias: [0.0, 0.0, 0.0] # Roll, Pitch, Yaw
            variance: [0.0, 0.0, 0.0] # Roll, Pitch, Yaw
          orientation_rate:
            bias: [0.0, 0.0, 0.0] # Roll rate, Pitch rate, Yaw rate
            variance: [0.0, 0.0, 0.0] # Roll rate, Pitch rate, Y



                
