################################
#   Default Parameters
################################

# "/**" is needed for nodes to find their params despite the "/vehicle0/<meta_package>/"<node_name>. the /**/ essentially leaves only the "node_name" as a key.
/**:
  filter_handler:
    ros__parameters:
      default_filter: "sample_and_hold"
      filters:
        - "sample_and_hold"
        - "low_pass"

  sample_and_hold:
    ros__parameters:
      node_frequency: 10.0
      neglect_current: false
      course_cf:
        use: false
        cutoff_frequency: 0.1 # Hz
      yaw_rate_kf:
        use: false  
      yaw_rate_lpf:
        use: false
        omega_cutoff: 0.4  # rad/s
        order: 1
        design: "butterworth" # design options ("butterworth", "bessel")
        method: "tustin" # descretization method ("tustin", "zoh", "euler")
      yaw_rate_notch_filter:
        use: true
        f0_hz: 0.318
        q: 1.0

  low_pass:
    ros__parameters:
      node_frequency: 10.0
      neglect_current: false
      position:
        omega_cutoff: 1.0
        order: 3
        design: "bessel" # design options ("butterworth", "bessel")
        method: "tustin" # descretization method ("tustin", "zoh", "euler")
      velocity:
        omega_cutoff: 1.0
        order: 3
        design: "bessel" # design options ("butterworth", "bessel")
        method: "tustin" # descretization method ("tustin", "zoh", "euler")
      orientation:
        omega_cutoff: 1.0
        order: 3
        design: "bessel" # design options ("butterworth", "bessel")
        method: "tustin" # descretization method ("tustin", "zoh", "euler")
      orientation_rate:
        omega_cutoff: 1.0
        order: 3
        design: "bessel" # design options ("butterworth", "bessel")
        method: "tustin" # descretization method ("tustin", "zoh", "euler")