################################
#   Default Parameters
################################

# "/**" is needed for nodes to find their params despite the "/vehicle0/<meta_package>/"<node_name>. the /**/ essentially leaves only the "node_name" as a key.
/**:
  filter_handler:
    ros__parameters:
      default_filter: "sample_and_hold"
      filters:
        - "sample_and_hold"
        - "low_pass"

  sample_and_hold:
    ros__parameters:
      node_frequency: 10.0
      neglect_current: false
      course_cf:
        use: false
        cutoff_frequency: 0.1 # Hz
      yaw_rate_kf:
        use: false  
      yaw_rate_lpf:
        use: false
        omega_cutoff: 0.4  # rad/s
        order: 1
        design: "butterworth" # design options ("butterworth", "bessel")
        method: "tustin" # descretization method ("tustin", "zoh", "euler")
      yaw_rate_notch_filter:
        use: true
        f0_hz: 0.318
        q: 1.0
      position_ekf:
        use: true
        gps_timeout_s: 3.0
        rpm_timeout_s: 0.2
        process_noise_pos: 0.1  
        process_noise_current: 0.01
        measurement_noise_pos: 1.0
        init_cov_pos: 25.0
        init_cov_current: 1.0
        rpm_min: -2000.0
        rpm_max: 2000.0
        rpm_rate_limit: 200.0 #  = 10 %/s
        rho: 1025.0
        prop_pitch: 0.381
        prop_diameter: 0.4318
        k_t_bp: 0.061461915
        m_u: 3100.0
        x_u: 0.0
        x_uu: -96.2270
        override_velocity: 1.71  # m/s at override_rpms (0.0 = disabled)
        override_rpms: 600.0    # RPM setpoint for calibration
        override_timeout_s: 5.0  # Time to stay in ±1% band before applying override

  filter_node:
    ros__parameters:
      node_frequency: 10.0
      publish_all_steps: true
      # sample_and_hold is always applied first implicitly.
      filters: 
        - "" ## this is needed because ROS2 is stupid and doesnt understand this an empty array of strings... might be fixed in the future 
        - "position_current_ekf"
      timeouts:
        imu: 1.0
        navsat: 2.0
        utm: 2.0
        rpm: 1.0
      plugins:
        position_current_ekf:
          override_position_state: true
          process_noise_pos: 0.1
          process_noise_current: 0.01
          measurement_noise_pos: 1.0
          init_cov_pos: 25.0
          init_cov_current: 1.0
          rpm_min: -2000.0
          rpm_max: 2000.0
          rpm_rate_limit: 200.0
          rho: 1025.0
          prop_pitch: 0.381
          prop_diameter: 0.4318
          k_t_bp: 0.061461915
          m_u: 3100.0
          x_u: 0.0
          x_uu: -96.2270
          override_velocity: 1.618
          override_rpms: 600.0
          override_timeout_s: 5.0
