################################
#   Default Parameters
################################
/**:
  pid:
    ros__parameters:
      node_frequency: 10.0
      course_control: false   # set to true to control course angle instead of yaw
      lpf_order: 3
      lpf_method: "tustin"
      lpf_design: "bessel"
      # Speeds (surge, sway, heave)
      surge:
        enabled: false
        kp: 10.0
        ki: 1.0
        lpf_wc: 31.4 # rad/s
        tau_min: -30.0 # N
        tau_max: 30.0 # N
      sway:
        enabled: false
        kp: 1.0
        ki: 1.0
        lpf_wc: 31.4 # rad/s
        tau_min: -20.0 # N
        tau_max: 20.0 # N
      heave:
        enabled: false
        kp: 1.0
        ki: 1.0
        lpf_wc: 31.4 # rad/s
        tau_min: -20.0 # N
        tau_max: 20.0 # N
      # Angles (yaw, pitch, roll)
      yaw:
        debug: true
        enabled: true
        # Following Gains are for:
        #   m_r = 88.0; N_r = 14.0; N_rr = 260.0; xi = 0.7; additional pole @ 10*xi*wn
        # wc = 0.2
        kp: 21.4
        ki: 2.1
        kd: 110.0
        # wc = 0.5
        # kp: 238.8929
        # ki: 77.4190
        # kd: 371.6111
        # wc = 0.6
        # kp: 344.0057
        # ki: 133.7800
        # kd: 445.9334
        # kffv_lin: 14.334052
        # kffv_sq: 260.675031
        # kffa: 88.478840
        kffv_lin: 0.0
        kffv_sq: 0.0
        kffa: 0.0
        lpf_wc: 1.0 # rad/s (2hz about the maximum possible given that sampling is 10hz)
        # lpf_wc: 12.5664 # rad/s (2hz about the maximum possible given that sampling is 10hz)
        tau_min: -6.0  # N.m (actual in simulation is 5.93)
        tau_max: 6.0 # N.m
      pitch:
        enabled: false
        kp: 1.0
        ki: 1.0
        kd: 1.0
        lpf_wc: 3.1416 # rad/s
        tau_min: -10.0 # N.m
        tau_max: 10.0 # N.m
      roll:
        enabled: false
        kp: 1.0
        ki: 1.0
        kd: 1.0
        lpf_wc: 3.1416 # rad/s
        tau_min: -10.0 # N.m
        tau_max: 10.0 # N.m
      # Angle rates (yaw rate, pitch rate, roll rate)
      yaw_rate:
        enabled: false
        kp: 1.0
        ki: 1.0
        lpf_wc: 31.4 # rad/s
        tau_min: -10.0 # N.m
        tau_max: 10.0 # N.m
      pitch_rate:
        enabled: false
        kp: 1.0
        ki: 1.0
        lpf_wc: 31.4 # rad/s
        tau_min: -10.0 # N.m
        tau_max: 10.0 # N.m
      roll_rate:
        enabled: false
        kp: 1.0
        ki: 1.0
        lpf_wc: 31.4 # rad/s
        tau_min: -10.0 # N
        tau_max: 10.0 # N-m
      # Full attitude (yaw, pitch and roll)
      attitude:
        enabled: false

  open_loop:
    ros__parameters:
      # Speeds (surge)
      surge:
        enabled: true
        gain: 1100.0
