################################
#   Default Parameters
################################

# "/**" is needed for nodes to find their params despite the "/vehicle0/<meta_package>/"<node_name>. the /**/ essentially leaves only the "node_name" as a key.
/**:
  filter_handler:
    ros__parameters:
      default_filter: "low_pass"
      filters:
        - "sample_and_hold"
        - "low_pass"

  sample_and_hold:
    ros__parameters:
      node_frequency: 10.0
      neglect_current: false
      yaw_rate_lpf:
        use_yaw_rate_lpf: true
        omega_cutoff: 0.628 # 0.1 Hz cutoff frequency
        order: 2
        design: "bessel" # design options ("butterworth", "bessel")
        method: "tustin" # descretization method ("tustin", "zoh", "euler")

  low_pass:
    ros__parameters:
      node_frequency: 10.0
      neglect_current: false
      position:
        omega_cutoff: 1.0
        order: 3
        design: "bessel" # design options ("butterworth", "bessel")
        method: "tustin" # descretization method ("tustin", "zoh", "euler")
      velocity:
        omega_cutoff: 1.0
        order: 3
        design: "bessel" # design options ("butterworth", "bessel")
        method: "tustin" # descretization method ("tustin", "zoh", "euler")
      orientation:
        omega_cutoff: 1.0
        order: 3
        design: "bessel" # design options ("butterworth", "bessel")
        method: "tustin" # descretization method ("tustin", "zoh", "euler")
      orientation_rate:
        omega_cutoff: 1.0
        order: 3
        design: "bessel" # design options ("butterworth", "bessel")
        method: "tustin" # descretization method ("tustin", "zoh", "euler")