################################
#
#   TODO: Description
#
################################

simulation:
  ros__parameters:
    param1: "test"
    list_of_params:
      - "abcd"
      - "efgh"
    param2: 1234